name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: [build, test]
    permissions:
      contents: read
      packages: write  # Required to push to GitHub Container Registry
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/my-app
          docker build -t my-app:latest .

      - name: Tag Docker image with commit SHA
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/my-app
          docker tag $IMAGE_NAME:latest my-app:${{ github.sha }}

      - name: Push Docker image (latest)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/my-app
          docker push my-app:latest

      - name: Push Docker image (commit SHA)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/my-app
          docker push my-app:${{ github.sha }}
